// This is a sample list. A comprehensive list would be much larger and might require more sophisticated matching.
// Keywords should be lowercase for case-insensitive matching.
export const NON_VEGAN_INGREDIENTS: string[] = [
  'milk',
  'lactose',
  'whey',
  'casein',
  'caseinate',
  'egg',
  'eggs',
  'albumin',
  'albumen',
  'honey',
  'beeswax',
  'royal jelly',
  'propolis',
  'gelatin',
  'collagen',
  'isinglass',
  'shellac',
  'carmine',
  'cochineal',
  'e120',
  'lanolin',
  'rennet',
  'animal fat',
  'lard',
  'tallow',
  'fish oil',
  'omega-3 (from fish)',
  'vitamin d3 (from lanolin)',
  'ghee',
  'butter',
  'cream',
  'yoghurt (unless specified vegan)',
  'yogurt (unless specified vegan)',
  'cheese (unless specified vegan)',
  'curds',
  'animal rennet',
  'castoreum',
  'musk',
  'suet',
  'bone char', // often used in sugar refining, though not an ingredient itself
  'bone phosphate',
  'e542'
];
